version: "3"
services:
    knu-shuttle-bus-db:
        container_name: knu-shuttle-bus-db
        ports:
            - 3306:3306
        networks:
            - knu-shuttle-bus-network
        volumes:
            - "./mysql/db:/var/lib/mysql"
            - "./mysql/initdb.d:/docker-entrypoint-initdb.d"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=knu_shuttle_bus
            - MYSQL_USER=knu_shuttle_bus_admin
            - MYSQL_PASSWORD=1111
        image: mysql
        healthcheck:                   
            test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
            timeout: 20s
            retries: 10

    knu-shuttle-bus-server:
        container_name: knu-shuttle-bus-server
        ports:
            - 8080:8080
        networks:
            - knu-shuttle-bus-network
        image: fight0105/knu-shuttle-bus-image:latest
        depends_on:
            knu-shuttle-bus-db:
                condition: service_healthy

networks:
    knu-shuttle-bus-network:

volumes:
    mysql-data:
      driver: local
    knu-shuttle-bus-server-image:
      driver: local